### ISSUE TITLE
Subclassing UIViewController instead of UICollectionViewController

### ISSUE THREAD

**Issue by walsh2000** [gleue/TGLStackedViewController#18]
Would you be opposed to a Pull Request which turns TGLStackedViewController into a subclass of UIViewController rather than a UICollectionViewController?

The benefit of this will be that subclasses could then easily manage additional subviews (such as an index-scrubber)

**Comment by annathomasQB** [comment]
Hi @walsh2000 , i too have the same requirement.. can you tell what you did for this?

**Comment by walsh2000** [comment]
I used "View Controller Containment" (using the TGLStackedViewController as a child VC)

Best of luck!

**Comment by annathomasQB** [comment]
Thanks!! okay will try that :+1:
