### ISSUE TITLE
Switching between stacked layout and flow layout

### ISSUE THREAD

**Issue by yuriferretti** [gleue/TGLStackedViewController#20]
Hi, first I'd like to congratulate you for the awesome control !!
In my app I'm trying to show all items in full size when one of them is tapped. I achieved the desired effect using UICollectionViewFlowLayout instead of TGLExposedLayout when one of the items is selected. But when I deselect it, switching back to TGLStackedLayout, the collection view is scrolled to a different position to what is expected and in most of times the item below the deselected item is missing, so I have to scroll the missing item off the screen to bring it back.

Does anyone have an idea to what could I do to fix it?

**Comment by gleue** [comment]
Have a look at TGLStackedViewController.m:159 in method -setExposedItemIndexPath:

There the previously saved contentOffset is used to compute the stacked layout. Maybe that's causing the effects you're experiencing?

**Comment by gleue** [comment]
I fixed an issue with content offset handling in 1.0.5. See method -targetContentOffsetForProposedContentOffset: in the Layout classes.

Does that fix it for you?
