### ISSUE TITLE
Item size

### ISSUE THREAD

**Issue by filipandrei87** [gleue/TGLStackedViewController#21]
Setting the item's size, on selection, exposes not only the selected card.
Also, when deselecting it, it scrolls offscreen. This was reproduced in the example project only by setting the item size.

**Comment by gleue** [comment]
What itemSizes did you use?

**Comment by filipandrei87** [comment]
view.bounds.size.width, 200

**Comment by gleue** [comment]
Issue should be fixed in 1.0.5
