### ISSUE TITLE
Support for multiple sections

### ISSUE THREAD

**Issue by beloso** [gleue/TGLStackedViewController#24]
Is there any chance for adding support for multiple sections?

**Comment by gleue** [comment]
What exactly do you have in mind? Any idea on how to separate the cards of different sections?

**Comment by TiagoVeloso** [comment]
The same way there is a property for the rop reveal. There could be a property for the section height. And take that into account when positioning the cells. Not sure if that's enough though.

**Comment by gleue** [comment]
So you'd have multiple stacks, one per section?

**Comment by TiagoVeloso** [comment]
Yes. That would be it.

I have been playing around with something like that. Prolly I can make a PR
to your project. I am still working on some bits.

**Comment by sstadelman** [comment]
@TiagoVeloso did you make any progress on this multiple sections concept?
