### ISSUE TITLE
topReveal not being respected.

### ISSUE THREAD

**Issue by NitWitStudios** [gleue/TGLStackedViewController#29]
I have tried to set a custom 'topReveal' height, but it is never changed:

        self.stackedLayout.topReveal = 50.0

Any ideas why?

**Comment by gleue** [comment]
Hm, works for me... Where exactly are you setting -topReveal?

If you only have a small number of items and TGLStackedLayout -fillHeight is YES it will overwrite the top reveal in an attempt to fill the entire view height.

**Comment by NitWitStudios** [comment]
@gleue Yup, that was it, forgot to remove the fillHeight code. Thanks!
