### ISSUE TITLE
TGLStackedViewController in Container View adds extra top margin, can't get rid of it.

### ISSUE THREAD

**Issue by NitWitStudios** [gleue/TGLStackedViewController#30]
Not sure if this is a problem with the library or just in general, but since I want to have some custom UI above/below the stacked view, I embed it inside a container view instead, but keep getting an extra ~50pts of top margin in the stacked view. Here is my basic setup:

    override func viewDidLoad() {
        super.viewDidLoad()
        self.automaticallyAdjustsScrollViewInsets = false
        self.unexposedItemsAreSelectable = true
        self.stackedLayout.alwaysBounce = true
        self.stackedLayout.layoutMargin.top = 0.0
        self.stackedLayout.topReveal = DNDarePackCellCompactHeight
        self.exposedTopOverlap = DNDarePackCellCompactHeight
        self.collectionView?.contentInset = UIEdgeInsetsZero
    }

And yes, ensured all auto layout constraints are correct. Right now there is a simple UILabel at the top of the main view controller (UIViewController), then the Container View (with embedded UICollectionViewController of a subclassed TGLStackedViewController) is flush at the bottom of that. The label is only 32.0pts in height, but the stacked view's first card is about ~80pts below it. One thing I do notice is that as I swipe the cards up, they do move up to the correct position. It seems like its just some weird inset/margin that is being set on the first card somehow.

Any suggestions?

**Comment by gleue** [comment]
What's the initial -contentOffset of the collection view?

**Comment by NitWitStudios** [comment]
Everything is set to 0 in storyboard.
