### ISSUE TITLE
Selector of UIButton is not calling

### ISSUE THREAD

**Issue by wajahatchaudhry** [gleue/TGLStackedViewController#31]
I've added the UIButton and assigned it's selector but whenever i clicked on button Card gets closed instead of calling UIButton selector.

**Comment by gleue** [comment]
Hm, it works fine for me. What I did in the sample:

* Added button to CardCell
* Add action to TGLCollectionViewCell
* Wired buttons TouchUpInside event to cell's action

**Comment by wajahatchaudhry** [comment]
i'm doing to same thing in my code and it's not working. Whenever i click the button it closes the card instead of calling selector of UIButton

**Comment by wajahatchaudhry** [comment]
Sorry it was my mistake. i was adding UIButton in UIImageView thats why it's selector were not calling.

**Comment by OtherF** [comment]
Maybe the problem with the conflicts between gestures?
Try to use this method in delegate (Swift):
'''swift
func gestureRecognizer(gestureRecognizer: UIGestureRecognizer, shouldRequireFailureOfGestureRecognizer otherGestureRecognizer: UIGestureRecognizer) -> Bool {
return true
}
'''
