### ISSUE TITLE
Could you make MOVE_ZOOM into a property?

### ISSUE THREAD

**Issue by KemalPajevic** [gleue/TGLStackedViewController#32]
First of all, thank you for a great control. Saved me a lot of time of coding something similar myself.

So, is there any particular reason why the MOVE_ZOOM value is defined in a macro in stead of being a configurable property like almost everything else?
In my case I want to actually zoom in when moving a card (i.e. make the view larger then the cell in stead of smaller). Right now I have manually added the classes to my project and changed the macro to 1.05 in stead of 0.95, but I would really like to avoid this since I prefer using CocoaPods.

**Comment by gleue** [comment]
Well, you're right. It should be a property and there's no real reason why it isn't ;)

**Comment by KemalPajevic** [comment]
Thanks. I had actually made the change myself after your answer, but just as I was about to commit SourceTree told me there was a new pull available :)

**Comment by gleue** [comment]
See 1.1.1 -- also updated pod
