### ISSUE TITLE
How can I disable cards pop-up

### ISSUE THREAD

**Issue by SKstark** [gleue/TGLStackedViewController#34]
Hi, everything is working well, but in my app I need to disable card's pop up animation, when click on it appears.
Can I somehow disable this animation?

**Comment by gleue** [comment]
Have a look at `TGLStackedViewController.collectionView:didSelectItemAtIndexPath:` in `TGLStackedViewController.m:219`. It's where the exposed item is set, which then triggers the layout change.

**Comment by SKstark** [comment]
Thank you very much!
