### ISSUE TITLE
Tappable area of stacked view not obeying visual zIndex

### ISSUE THREAD

**Issue by DavidTop** [gleue/TGLStackedViewController#38]
When calling `func moveItemAtIndexPath(indexPath: NSIndexPath, toIndexPath newIndexPath: NSIndexPath)`the zIndex of the cards looks good visually, but very often I notice that tapping on a card will result in the card behind in the stack responding to the tap instead.

I noticed that opening up the Interface Inspector in Xcode reveals that the zIndex of the views themselves are infact incorrect. Even though it looks perfect on the simulator and a device. 

After doing some research I've discovered that the zIndex of a layer doesn't infact modify the response order of the cells in regards to which cell is on top when a tap event is trigger. Modifying the zIndex instead only visually changes the zIndex of the layer.

I've been working on trying to fix this for a few days. Do you have any ideas on how to fix this issue?

**Comment by gleue** [comment]
Hm, that's bad news. I never ran into similar problems, yet. I'll try to reproduce the situation.

As for a fix: Since the issue does only occur after reordering the cards, would a "silent" `reloadData` help to fix the ordering somehow?

**Comment by gleue** [comment]
I fixed a LARGER problem with z ordering, especially when switching layouts. Maybe that also solves your problem?
