### ISSUE TITLE
would anybody be willing to write this in Swift 3??  

### ISSUE THREAD

**Issue by bbongrip** [gleue/TGLStackedViewController#42]
I've been looking for something like this but I dont know C,  is there anyone willing to convert this code to swift 3?

**Comment by mejiagarcia** [comment]
Hi there, here with the same question, if have something please let me know.

**Comment by gleue** [comment]
Does Mix&Match (e.g. using a bridging header) not work for you?

**Comment by bbongrip** [comment]
hi guys.  I'm very new to coding Gleue, so I'm not quite sure what a bridged header is.  However i did find this site that converts Objective C to swift!!     https://objectivec2swift.com/#/home/converter/
It's very cool and seems to be very reliable when converting complex code.  Hope this helps somebody.

**Comment by gleue** [comment]
Have a look at https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/BuildingCocoaApps/index.html
