### ISSUE TITLE
Give space between cells

### ISSUE THREAD

**Issue by tapan-nathvani** [gleue/TGLStackedViewController#44]
How can i give few pixel space between each cell ? And from bottom to top cells.. width should decreased... how can i achieve this ?

**Comment by gleue** [comment]
You could try setting an item size and making the cells' main view smaller than that.

**Comment by gleue** [comment]
For the decreasing width you'd have to adjust `-prepareLayout` in the two Layout classes.

**Comment by tapan-nathvani** [comment]
Yes i changed frame in prepareLayout and it works fine. Thanks :)
