### ISSUE TITLE
An exception occurs under the iOS11

### ISSUE THREAD

**Issue by czeludzki** [gleue/TGLStackedViewController#45]
Thank you very much.
Although I didn't use your framework directly, but I really got a lot of inspiration form them.

But now, under the iOS 11 system, I set zIndex and set transform for the attributes in the 
`- (UICollectionViewLayoutAttributes *)layoutAttributesForInteractivelyMovingItemAtIndexPath:(NSIndexPath *)indexPath withTargetPosition:(CGPoint)position
`
it doesn't work..

I'm not sure it's the bug of the iOS11, but it's been bothering me for days...

**Comment by gleue** [comment]
I can reproduce the issue here, too :(

It seems the `layoutAttributes` are applied only a random point later in time. I am investigating...

**Comment by gleue** [comment]
The only reliable way I found to dat is to use drag and drop on iOS 11 -> see `2.2`

**Comment by czeludzki** [comment]
The problem has been solved, Thank you! 😆

**Comment by gleue** [comment]
Did zou manage to solve it in a different way or are you using drag and drop, too?

**Comment by czeludzki** [comment]
I refer to your code, using drag and drop.
Because of IOS 11, this seems to be the best solution.
Thank you very much!
I found that if I closed the issue, I couldn't find it in the issues list, so I opened it again..

**Comment by gleue** [comment]
Just remove the issue filter `is:open` ;-)
