### ISSUE TITLE
ios 11 dragitems

### ISSUE THREAD

**Issue by shinshouri** [gleue/TGLStackedViewController#48]
hi gleue,

im update my tglstackedviewcontroller with new version 2.2.2
but i got problem with new behavior in 2.2.2.
when i drag item it shrink when moving the drag item.
so can u tell me where should i change the code to make the drag item just like previous behavior (like version 2.0)

Thank you

**Comment by shinshouri** [comment]
i already trying to change 
[UIBezierPath bezierPathWithRoundedRect:CGRectMake(0, 0, _cardSize.width, 200) cornerRadius:10.0]
it change the shape but it still got shrink.

**Comment by gleue** [comment]
Did you use `[collectionView:dragPreviewParametersForItemAtIndexPath:](https://developer.apple.com/documentation/uikit/uicollectionviewdragdelegate/2897459-collectionview?language=objc)`?

**Comment by gleue** [comment]
Maybe adding your own `[previewProvider](https://developer.apple.com/documentation/uikit/uidragitem/2890972-previewprovider?language=objc)` might also help when creating the `UIDragItems`

**Comment by shinshouri** [comment]
Thanks for ur reply...
i already solve my problem by removing 
-(NSArray<UIDragItem *> *)collectionView:(UICollectionView *)collectionView itemsForBeginningDragSession:(id<UIDragSession>)session atIndexPath:(NSIndexPath *)indexPath NS_AVAILABLE_IOS(11) 
in TGLViewController...

Thanks...
