### ISSUE TITLE
Getting error collection view layout

### ISSUE THREAD

**Issue by Ruchi0712** [gleue/TGLStackedViewController#54]
When I run an application after implement get error 
"Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'TGLStackedViewController collection view layout is not a TGLStackedLayout' "
I don't understand what's going wrong

**Comment by gleue** [comment]
**Using storyboards**

When you put a `TGLStackedViewController` in a storyboard you have to make sure that the `UICollectionView`s layout set to `Custom` with class `TGLStackedLayout`.

<img width="257" alt="Bildschirmfoto 2019-05-27 um 17 10 09" src="https://user-images.githubusercontent.com/3965904/58428283-4a3bc880-80a2-11e9-8e45-ebc408e2f152.png">

See `Main.storyboard` in the example project.

**Using code**

When your create a `TGLStackedViewController` in code make sure to use `- (instancetype)initWithCollectionViewLayout:(UICollectionViewLayout *)layout` with a proper `TGLStackedLayout` instance -- see `TGLStackedViewController.m:66`

**Comment by Ruchi0712** [comment]
@gleue  thanks working 🙂
