### ISSUE TITLE
ios6 and ios6.1 running effect

### ISSUE THREAD

**Issue by ouguoquan** [gleue/TGLStackedViewController#7]
This project  support ios6 and ios6.1 ，bug  the running effect is different from ios7 above?  In ios6 adn ios6.1 ,It can  launch but it can't take back.

**Comment by jomnius** [comment]
Bump. Any official fix?

**Comment by gleue** [comment]
Not yet. To be honest, I am not going to dive into this issue since I don't need iOS 6 support.

But if you'd like to investigate, I'd be more than happy :-)

**Comment by jomnius** [comment]
Compiled with Xcode6 for base target iOS7, run in iPhone6 with iOS8. I think the problem appeared after I added background view into cards. However latest UI spec seems to be using tableView, so not very urgent. Just don't like unsolved problems :)

Couldn't get smooth animation with the tips here and at SO, so was wondering, if you (anyone) ever solved this. If we get back to non-table "cards" UI, might take another look. Thanx for status update!

**Comment by gleue** [comment]
Dropped iOS 6 support in version 1.1
